### ISSUE TITLE
Theme Upload Request

### ISSUE THREAD

**Issue by GodNops** [DS-Homebrew/twlmenu-extras#107]
**Name**
Eeveelution Fan

**Author**
GodNops

**Description**
This theme showcases eevee and its evolutions. it has just some basics right now:

backgrounds, battery and sound icons, and music (currently not included as it is too big for here)

I plan on continuing to update it with new sound bank and more gui changes.

**Categories**
Pokemon, eevee, eeveelutions

**Icon**
![eevee](https://user-images.githubusercontent.com/117409729/199847151-2e537156-0549-4f00-b9d5-d4789101ba00.png)

**Screenshots**

Screenshots will be uploaded soon

**Theme Download**

[CustomMusicEevee v1.zip](https://github.com/DS-Homebrew/twlmenu-extras/files/9933487/CustomMusicEevee.v1.zip)

**Comment by NightScript370** [comment]
> I plan on continuing to update it with new sound bank and more gui changes.
Would you be interested in publishing that version when it's ready? I would think that would be better than making an update.
