### ISSUE TITLE
DSi Skin Submit

### ISSUE THREAD

**Issue by cyberbasty** [DS-Homebrew/twlmenu-extras#124]
Elh Melizée

Cyberbasty

It's a theme about Elh Melizée, one of the main characters of Solatorobo Red the huner.
Made by a french fan of the game.
https://github.com/cyberbasty/Elh-Melizee-Solatorobo-theme-dsi/releases/tag/V1.1

["Solatorobo","Elh","Gray","Dark"]

![Elh face](https://user-images.githubusercontent.com/82098265/211174399-7d6faa5b-63c2-44a8-a807-aca134d2286f.png)

![image](https://user-images.githubusercontent.com/82098265/211174417-9cee81a3-f86a-48c7-84af-0b50e2f2ed2a.png)

[Elh Mélizée Solatorobo.zip](https://github.com/DS-Homebrew/twlmenu-extras/files/10367405/Elh.Melizee.Solatorobo.zip)

**Comment by Epicpkmn11** [comment]
Added in 14ab9a41332a2fd72f18e2bd12d7f5ab8cfb2097
