### ISSUE TITLE
ToneSynthDS icon

### ISSUE THREAD

**Issue by 0x0ryba** [DS-Homebrew/twlmenu-extras#152]
**Name**
ToneSynthDS

**Author**
ryba

**Description**

**Categories**
icon

**Icon**
![ToneSynthDS nds](https://user-images.githubusercontent.com/130148135/230791421-8573ae68-6041-4a8c-9f0f-64a2c793ea75.png)

**Screenshots**

**Comment by Epicpkmn11** [comment]
If you're doing more can you put them all in one issue? that'll just be easier to keep track of

**Comment by 0x0ryba** [comment]
Yes. Sorry. Didn't have any order in it, so this is how it ended. Next time I'll keep it more organized.
