### ISSUE TITLE
[Security] Workflow update.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Freakston** [DS-Homebrew/twlmenu-extras#33]
The workflow update.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by Epicpkmn11** [comment]
We can't use actions/checkout@2 since devkitPro's docker image is too outdated

**Comment by lifehackerhansol** [comment]
It seems to work fine: https://github.com/lifehackerhansol/twlmenu-extras

**Comment by Epicpkmn11** [comment]
That one doesn't have submodules, submodules are the issue

**Comment by Epicpkmn11** [comment]
Oh I missed which repo this one on, so I guess it's fine here but all of the other repos that use devkitPro's docker and submodules this is an issue for
