### ISSUE TITLE
okakoro theme

### ISSUE THREAD

**Issue by swonker** [DS-Homebrew/twlmenu-extras#88]
**Name**
Okakoro

**Author**
swonker

**Description**
Nekomata Okayu x Inugami Korone themed skin, with background and bgm.

**Categories**
hololive, hololive gamers

**Icon**
![okakoro](https://user-images.githubusercontent.com/111015093/184008318-e011597c-a49e-40c4-971f-5c8316c268a3.png)

**Screenshots**

**Comment by swonker** [comment]
I, a fool, forgot to attach the zip.
[okakoro.zip](https://github.com/DS-Homebrew/twlmenu-extras/files/9303662/okakoro.zip)

**Comment by lifehackerhansol** [comment]
yes

**Comment by lifehackerhansol** [comment]
There's a lot of extra files here. `skin-examples.zip` for example isn't needed in `volume`. We also don't really need any of the samples you have either, just `bgm.pcm.raw` and `sfx.bin` suffices.

And many `_.DS_store` files. (idk if you can delete them from a Mac though)

**Comment by swonker** [comment]
My bad, is this better? I tried not to mess with deleting things I wasn't sure about, so just let me know if you need me to change anything else.
[okakoro.zip](https://github.com/DS-Homebrew/twlmenu-extras/files/9304359/okakoro.zip)
